version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout

      - run:
          name: "Install dependencies"
          command: npm install

      - run:
          name: "Build React app"
          command: npm run build

workflows:
  react-integration:
    jobs:
      - build-and-test
