version: 2.1

jobs:
  build-and-test:
    docker:

      - image: cimg/node:20.11  # includes node + npm


    steps:
      - checkout

      - run:
          name: "Install dependencies"
          command: npm install

      - run:
          name: "Build React app"

          command: CI=false npm run build

workflows:
  react-integration:
    jobs:
      - build-and-test
